name: week007
version: 1.0.0
config-version: 2
profile: week007
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  week007:
    +materialized: view
